"""Build a standalone Windows executable containing one verified HBC program."""

from __future__ import annotations

import importlib.metadata
import importlib.util
import hashlib
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from .bytecode import CodeObject, loads
from .environment import external_source_root, hython_home, is_frozen


class ExeBuildError(RuntimeError):
    pass


def resolve_entry(source: Path, entry: str | None = None) -> tuple[Path,Path]:
    """Resolve a single HBC or a project directory and its module root."""
    source=source.resolve()
    if source.is_file():
        return source,source.parent
    if not source.is_dir():
        raise ExeBuildError(f"HBC 입력을 찾을 수 없습니다: {source}")
    if entry:
        candidate=(source/entry).resolve()
        if source not in candidate.parents or not candidate.is_file():
            raise ExeBuildError(f"프로젝트 entry를 찾을 수 없습니다: {entry}")
        return candidate,source
    candidates=[source/"main.hbc",source/"메인.hbc"]
    found=[path for path in candidates if path.is_file()]
    if not found:
        top=sorted(source.glob("*.hbc"))
        if len(top)==1:
            found=top
    if len(found)!=1:
        raise ExeBuildError("프로젝트 entry를 결정할 수 없습니다. --entry를 지정하세요.")
    return found[0],source


def imported_modules(code: CodeObject) -> set[str]:
    """Collect Python import roots, including nested Hython code objects."""
    found: set[str]=set()
    seen: set[int]=set()

    def visit(current: CodeObject) -> None:
        if id(current) in seen:
            return
        seen.add(id(current))
        for instruction in current.instructions:
            if instruction and instruction[0]=="IMPORT" and len(instruction)>1 and isinstance(instruction[1],str):
                name=instruction[1].lstrip(".").split(".",1)[0]
                if name and re.fullmatch(r"[A-Za-z_]\w*",name):
                    found.add(name)
            elif instruction and instruction[0]=="IMPORT_FROM" and len(instruction)>1 and isinstance(instruction[1],dict):
                name=str(instruction[1].get("module","")).lstrip(".").split(".",1)[0]
                if name and re.fullmatch(r"[A-Za-z_]\w*",name):
                    found.add(name)
            for argument in instruction[1:]:
                visit_value(argument)
        for constant in current.constants:
            visit_value(constant)

    def visit_value(value) -> None:
        if isinstance(value,CodeObject):
            visit(value)
        elif isinstance(value,dict):
            if {"name","parameters","constants","instructions"} <= value.keys():
                try:
                    visit(CodeObject.from_dict(value))
                except (KeyError,TypeError,ValueError):
                    pass
            else:
                for item in value.values(): visit_value(item)
        elif isinstance(value,(list,tuple)):
            for item in value: visit_value(item)

    visit(code)
    return found


def _launcher_source(hbc: bytes) -> str:
    return (
        "# generated by Hython; the HBC payload is integrity-checked again at startup\n"
        "import sys\n"
        "from pathlib import Path\n"
        "from hython.bytecode import loads\n"
        "from hython.vm import VM\n"
        f"HBC = bytes.fromhex({hbc.hex()!r})\n"
        "def main():\n"
        "    root=Path(sys.executable).resolve().parent\n"
        "    frozen=Path(getattr(sys,'_MEIPASS',root))\n"
        "    bundle=frozen/'hbc_modules'\n"
        "    import os; os.environ.setdefault('HYTHON_RESOURCE_ROOT',str(frozen/'resources'))\n"
        "    VM([bundle,root]).run(loads(HBC))\n"
        "if __name__ == '__main__':\n"
        "    main()\n"
    )


def _pyinstaller_command(
    launcher: Path, *, name: str, work: Path, console: bool, icon: Path | None,
    imports: set[str], source_root: Path,
    modules: list[tuple[Path,Path]],
    resources: list[tuple[Path,Path]], onefile: bool = True,
    version_file: Path | None = None, excludes: set[str] = frozenset(),
    prefix: list[str] | None = None,
) -> list[str]:
    command=[
        *(prefix or [sys.executable,"-m","PyInstaller"]),"--noconfirm","--clean",
        "--onefile" if onefile else "--onedir",
        "--name",name,"--distpath",str(work/"dist"),"--workpath",str(work/"build"),
        "--specpath",str(work/"spec"),"--paths",str(source_root),
        "--console" if console else "--windowed",
    ]
    distributions=importlib.metadata.packages_distributions()
    if "tkinter" in imports:
        imports.update({"tkinter.ttk","tkinter.messagebox","tkinter.filedialog","tkinter.colorchooser","tkinter.simpledialog"})
    for module in sorted(imports):
        command.extend(["--hidden-import",module])
        if module in distributions:
            command.extend(["--collect-all",module])
    for module in sorted(excludes):
        command.extend(["--exclude-module",module])
    if icon is not None:
        command.extend(["--icon",str(icon.resolve())])
    for module,relative in modules:
        destination=Path("hbc_modules")/relative.parent
        command.extend(["--add-data",f"{module.resolve()}{os.pathsep}{destination.as_posix()}"])
    for resource,destination in resources:
        staged=work/"resource-stage"/destination
        staged.parent.mkdir(parents=True,exist_ok=True)
        if resource.is_dir():
            shutil.copytree(resource,staged)
        else:
            shutil.copy2(resource,staged)
        target=Path("resources")/destination.parent
        command.extend(["--add-data",f"{staged.resolve()}{os.pathsep}{target.as_posix()}"])
    if version_file is not None:
        command.extend(["--version-file",str(version_file)])
    command.append(str(launcher))
    return command


def _pyinstaller_runtime() -> tuple[list[str],dict[str,str] | None,Path]:
    if not is_frozen():
        if importlib.util.find_spec("PyInstaller") is None:
            raise ExeBuildError("PyInstaller가 없습니다: python -m pip install pyinstaller")
        return [sys.executable,"-m","PyInstaller"],None,external_source_root()
    from .runtime_manager import find_manager
    tools=hython_home()/"tools"/"pyinstaller"
    if not (tools/"PyInstaller").is_dir():
        tools.mkdir(parents=True,exist_ok=True)
        result=subprocess.run([
            find_manager(),"exec","-V:default","-m","pip","install","--target",str(tools),"pyinstaller>=6.16"
        ])
        if result.returncode:
            raise ExeBuildError("독립 EXE용 PyInstaller 도구 설치에 실패했습니다.")
    env=os.environ.copy()
    env["PYTHONPATH"]=str(tools)+os.pathsep+env.get("PYTHONPATH","")
    return [find_manager(),"exec","-V:default","-m","PyInstaller"],env,external_source_root()


def _validate_resources(resources: list[tuple[Path,Path]]) -> list[tuple[Path,Path]]:
    result=[]
    for source,destination in resources:
        if not source.exists():
            raise ExeBuildError(f"리소스를 찾을 수 없습니다: {source}")
        if destination.is_absolute() or ".." in destination.parts:
            raise ExeBuildError(f"안전하지 않은 리소스 대상 경로: {destination}")
        result.append((source,destination))
    return result


def _version_source(metadata: dict[str,str]) -> str:
    version=metadata.get("version","1.0.0.0")
    try:
        numbers=[int(item) for item in version.split(".")]
    except ValueError as exc:
        raise ExeBuildError("EXE 버전은 숫자와 점만 사용할 수 있습니다.") from exc
    if not 1<=len(numbers)<=4 or any(item<0 or item>65535 for item in numbers):
        raise ExeBuildError("EXE 버전은 0~65535의 숫자 1~4개여야 합니다.")
    numbers=(numbers+[0]*4)[:4]; dotted=".".join(map(str,numbers))
    product=metadata.get("product",metadata.get("name","Hython Program"))
    description=metadata.get("description",product); company=metadata.get("company","")
    copyright_=metadata.get("copyright",""); filename=metadata.get("filename","program.exe")
    pairs={"CompanyName":company,"FileDescription":description,"FileVersion":dotted,
           "InternalName":metadata.get("name",Path(filename).stem),"LegalCopyright":copyright_,
           "OriginalFilename":filename,"ProductName":product,"ProductVersion":dotted}
    strings=",\n".join(f"StringStruct({key!r}, {value!r})" for key,value in pairs.items())
    return ("VSVersionInfo(ffi=FixedFileInfo(filevers="+repr(tuple(numbers))+", prodvers="+repr(tuple(numbers))+
            ", mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0,0)), "
            "kids=[StringFileInfo([StringTable('040904B0',["+strings+"]) ]), VarFileInfo([VarStruct('Translation',[1033,1200])])])\n")


def _sign(executable: Path, pfx: Path, password_env: str | None, timestamp_url: str) -> None:
    tool=shutil.which("signtool")
    if not tool:
        raise ExeBuildError("signtool을 찾을 수 없습니다. Windows SDK를 설치하세요.")
    if not pfx.is_file():
        raise ExeBuildError(f"코드 서명 인증서를 찾을 수 없습니다: {pfx}")
    command=[tool,"sign","/fd","SHA256","/f",str(pfx.resolve())]
    if password_env:
        password=os.environ.get(password_env)
        if password is None:
            raise ExeBuildError(f"서명 암호 환경 변수가 없습니다: {password_env}")
        command.extend(["/p",password])
    if timestamp_url:
        command.extend(["/tr",timestamp_url,"/td","SHA256"])
    command.append(str(executable))
    result=subprocess.run(command,text=True,capture_output=True)
    if result.returncode:
        detail=(result.stderr or result.stdout).strip().splitlines()
        raise ExeBuildError("Authenticode 서명 실패: "+(detail[-1] if detail else "알 수 없는 오류"))


def create_archive(artifact: Path, archive: Path) -> tuple[Path,Path]:
    archive=archive.resolve()
    if archive.suffix.lower() != ".zip": archive=archive.with_suffix(".zip")
    archive.parent.mkdir(parents=True,exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="hython-archive-") as directory:
        temporary=Path(directory)/archive.name
        if artifact.is_dir():
            shutil.make_archive(str(temporary.with_suffix("")),"zip",artifact.parent,artifact.name)
        else:
            with __import__("zipfile").ZipFile(temporary,"w",__import__("zipfile").ZIP_DEFLATED) as bundle:
                bundle.write(artifact,artifact.name)
        temporary.replace(archive)
    digest=hashlib.sha256(archive.read_bytes()).hexdigest()
    checksum=archive.with_suffix(archive.suffix+".sha256")
    checksum.write_text(f"{digest}  {archive.name}\n",encoding="ascii")
    return archive,checksum


def build_exe(
    hbc_path: Path, output: Path, *, console: bool = True, icon: Path | None = None,
    module_root: Path | None = None, resources: list[tuple[Path,Path]] | None = None,
    onefile: bool = True, metadata: dict[str,str] | None = None,
    excludes: set[str] | None = None, sign_pfx: Path | None = None,
    sign_password_env: str | None = None,
    timestamp_url: str = "http://timestamp.digicert.com",
) -> Path:
    if os.name != "nt":
        raise ExeBuildError("현재 EXE 빌더는 Windows만 지원합니다.")
    prefix,build_env,source_root=_pyinstaller_runtime()
    if icon is not None and not icon.is_file():
        raise ExeBuildError(f"아이콘 파일을 찾을 수 없습니다: {icon}")
    try:
        hbc=hbc_path.read_bytes()
    except OSError as exc:
        raise ExeBuildError(f"HBC 파일을 읽을 수 없습니다: {exc}") from exc
    code=loads(hbc)
    module_root=(module_root or hbc_path.parent).resolve()
    if not module_root.is_dir():
        raise ExeBuildError(f"HBC 모듈 루트를 찾을 수 없습니다: {module_root}")
    modules: list[tuple[Path,Path]]=[]
    resources=_validate_resources(resources or [])
    imports=imported_modules(code)
    for module in sorted(module_root.rglob("*.hbc")):
        if module.resolve()==hbc_path.resolve():
            continue
        try:
            module_code=loads(module.read_bytes())
        except (OSError,ValueError) as exc:
            raise ExeBuildError(f"번들 HBC 모듈 검증 실패: {module}: {exc}") from exc
        modules.append((module,module.relative_to(module_root)))
        imports.update(imported_modules(module_code))
    local_roots={relative.parts[0].removesuffix(".hbc") for _,relative in modules if relative.parts}
    imports.difference_update(local_roots)
    output=output.resolve()
    output.parent.mkdir(parents=True,exist_ok=True)
    safe_name=re.sub(r"[^A-Za-z0-9_.-]","_",output.stem) or "hython_program"
    with tempfile.TemporaryDirectory(prefix="hython-exe-build-") as directory:
        work=Path(directory); launcher=work/"launcher.py"
        launcher.write_text(_launcher_source(hbc),encoding="utf-8",newline="\n")
        version_file=None
        if metadata:
            version_file=work/"version_info.txt"
            version_file.write_text(_version_source(metadata|{"filename":output.name}),encoding="utf-8")
        command=_pyinstaller_command(
            launcher,name=safe_name,work=work,console=console,icon=icon,
            imports=imports,source_root=source_root,modules=modules,
            resources=resources,onefile=onefile,version_file=version_file,
            excludes=excludes or set(),
            prefix=prefix,
        )
        # Frozen Hython runs in UTF-8 mode, while Windows build tools may emit
        # CP949/OEM bytes.  A diagnostic stream must never crash the reader
        # thread after an otherwise successful build.
        result=subprocess.run(
            command,text=True,capture_output=True,errors="replace",env=build_env
        )
        if result.returncode:
            detail=(result.stderr or result.stdout).strip().splitlines()
            raise ExeBuildError("PyInstaller 빌드 실패: "+(detail[-1] if detail else "알 수 없는 오류"))
        built=(work/"dist"/(safe_name+".exe")) if onefile else (work/"dist"/safe_name/(safe_name+".exe"))
        if not built.is_file() or built.stat().st_size<1024:
            raise ExeBuildError("PyInstaller가 유효한 EXE를 생성하지 않았습니다.")
        if onefile:
            handle,temporary=tempfile.mkstemp(prefix=output.name+".",suffix=".tmp",dir=output.parent)
            os.close(handle); temporary_path=Path(temporary)
            try:
                shutil.copy2(built,temporary_path)
                if sign_pfx: _sign(temporary_path,sign_pfx,sign_password_env,timestamp_url)
                temporary_path.replace(output)
            except BaseException:
                temporary_path.unlink(missing_ok=True); raise
        else:
            built_dir=built.parent; staging=Path(tempfile.mkdtemp(prefix=output.name+".",dir=output.parent))
            backup=None
            try:
                shutil.rmtree(staging); shutil.copytree(built_dir,staging)
                if sign_pfx: _sign(staging/(safe_name+".exe"),sign_pfx,sign_password_env,timestamp_url)
                if output.exists():
                    backup=output.with_name(output.name+".previous")
                    if backup.exists(): shutil.rmtree(backup)
                    output.replace(backup)
                staging.replace(output)
                if backup: shutil.rmtree(backup)
            except BaseException:
                shutil.rmtree(staging,ignore_errors=True)
                if backup and backup.exists() and not output.exists(): backup.replace(output)
                raise
    return output
