<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>..\..\assets\hython.ico</ApplicationIcon>
    <AssemblyName>HythonStudio</AssemblyName>
    <RootNamespace>HythonStudio</RootNamespace>
    <Version>1.0.2</Version>
    <Product>Hython Studio</Product>
    <Company>Kooyoseb</Company>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <EmbeddedResource Include="Resources\Hython.xshd" />
    <Resource Include="..\..\assets\hython-icon.png"
              Link="Resources\hython-icon.png" />
  </ItemGroup>
</Project>
